version=1
source_format=packwiz
source=https://raw.githubusercontent.com/SJMC-Dev/SMP3-modpack/refs/heads/release/pack.toml
preset=minecraft
require_successful_update=true

[branding]
modpack_name=SMP 3

;[colors]
;background = F8FAFC
;title = 0F172A
;subtitle = 64748B
;progress = 0EA5E9
;progress_track = E2E8F0
;dialog = 334155
;button = 0069A8
;button_text = FFFFFF
;question = 9333EA
;info = 0EA5E9
;warning = D97706
;error = DC2626

;[http]
;proxy=none

;[flavors]
;optimization_and_shaders=sodium_iris_off
;distant_horizons=distant_horizons_off
