[modName]
	# 名称：模组名称格式
	# 描述：用于JEI界面提示框中模组名称的格式。留空以禁用。
	# 有效值：A chat formatting string.
	# Use these formatting colors:
	# BLACK DARK_BLUE DARK_GREEN DARK_AQUA DARK_RED DARK_PURPLE GOLD GRAY DARK_GRAY BLUE GREEN AQUA RED LIGHT_PURPLE YELLOW WHITE
	# With these formatting options:
	# OBFUSCATED BOLD STRIKETHROUGH UNDERLINE ITALIC
	# 默认值：BLUE ITALIC
	modNameFormat = 


