# Early loading screen configuration file
# enable_entrypoint_information default: true
# enable_mixin_pretransform default: false
# allow_early_window_close default: true
# window_creation_point available [default] options: postModLoading mixinEarly [mixinLoad] preLaunch mcEarly off
#
#Mon Apr 28 22:54:07 CST 2025
allow_early_window_close=true
enable_entrypoint_information=true
enable_mixin_pretransform=true
window_creation_point=default
